"""init_schema

Revision ID: 698184e64da9
Revises: 
Create Date: 2026-01-01 09:21:16.180021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698184e64da9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ===============================
    # TABLES NOUVELLES (SAFE)
    # ===============================

    op.create_table(
        'audit_log',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('actor_type', sa.String(20)),
        sa.Column('actor_id', sa.Integer()),
        sa.Column('event', sa.String(100)),
        sa.Column('payload', sa.JSON()),
        sa.Column('ip_address', sa.String(50)),
        sa.Column('created_at', sa.DateTime()),
    )

    op.create_table(
        'risk_event',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('reference', sa.String(100)),
        sa.Column('provider', sa.String(50)),
        sa.Column('ip_address', sa.String(50)),
        sa.Column('risk_type', sa.String(50)),
        sa.Column('risk_score', sa.Integer()),
        sa.Column('details', sa.Text()),
        sa.Column('created_at', sa.DateTime()),
    )
    op.create_index('ix_risk_event_reference', 'risk_event', ['reference'])

    op.create_table(
        'payment_event',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('transaction_reference', sa.String(100)),
        sa.Column('provider', sa.String(50)),
        sa.Column('event_type', sa.String(50)),
        sa.Column('payload', sa.JSON()),
        sa.Column('ip_address', sa.String(45)),
        sa.Column('nonce', sa.String(128), unique=True),
        sa.Column('created_at', sa.DateTime()),
        sa.UniqueConstraint(
            'transaction_reference', 'event_type', 'provider',
            name='uq_event_once'
        )
    )

    op.create_table(
        'admin_user',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('utilisateur.id'), unique=True),
        sa.Column('role', sa.String(20)),
        sa.Column('actif', sa.Boolean(), default=True),
        sa.Column('created_at', sa.DateTime()),
    )

    op.create_table(
        'admin_action',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('admin_id', sa.Integer(), sa.ForeignKey('admin_user.id')),
        sa.Column('action_type', sa.String(50)),
        sa.Column('target_type', sa.String(50)),
        sa.Column('target_reference', sa.String(100)),
        sa.Column('reason', sa.Text()),
        sa.Column('ip_address', sa.String(50)),
        sa.Column('created_at', sa.DateTime()),
    )

    op.create_table(
        'refund',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('transaction_id', sa.Integer(), sa.ForeignKey('transaction.id')),
        sa.Column('amount', sa.Float()),
        sa.Column('reason', sa.Text()),
        sa.Column('admin_id', sa.Integer(), sa.ForeignKey('admin_user.id')),
        sa.Column('status', sa.String(20)),
        sa.Column('created_at', sa.DateTime()),
    )

    op.create_table(
        'ledger_entry',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('reference', sa.String(100), nullable=False),
        sa.Column('transaction_id', sa.Integer(), sa.ForeignKey('transaction.id')),
        sa.Column('conversion_id', sa.Integer(), sa.ForeignKey('conversion.id')),
        sa.Column('paiement_id', sa.Integer(), sa.ForeignKey('paiement.id')),
        sa.Column('compte', sa.String(50), nullable=False),
        sa.Column('sens', sa.String(6), nullable=False),
        sa.Column('montant', sa.Float(), nullable=False),
        sa.Column('devise', sa.String(10), nullable=False),
        sa.Column('provider', sa.String(50)),
        sa.Column('description', sa.String(255)),
        sa.Column('created_at', sa.DateTime()),
    )
    op.create_index('ix_ledger_entry_reference', 'ledger_entry', ['reference'])

    # ===============================
    # AJOUTS SAFE (sans DROP)
    # ===============================

    with op.batch_alter_table('paiement') as batch:
        batch.add_column(sa.Column('idempotency_key', sa.String(100), nullable=True))
        batch.create_index('ix_paiement_idempotency_key', ['idempotency_key'], unique=True)

    with op.batch_alter_table('utilisateur') as batch:
        batch.create_index('ix_utilisateur_email', ['email'], unique=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.create_unique_constraint('utilisateur_email_key', 'utilisateur', ['email'])
    op.alter_column('utilisateur', 'mot_de_passe',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_constraint('uq_rate_pair', 'rate', type_='unique')
    op.create_unique_constraint('uq_pair', 'rate', ['from_currency', 'to_currency'])
    op.drop_constraint(None, 'paiement', type_='unique')
    op.drop_constraint(None, 'paiement', type_='unique')
    op.drop_index(op.f('ix_paiement_idempotency_key'), table_name='paiement')
    op.create_index('uq_paiement_tx_ref', 'paiement', ['transaction_reference'], unique=True)
    op.drop_column('paiement', 'idempotency_key')
    op.drop_index(op.f('ix_conversion_reference'), table_name='conversion')
    op.create_unique_constraint('conversion_reference_key', 'conversion', ['reference'])
    op.alter_column('conversion', 'to_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('conversion', 'from_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint(None, 'compte', type_='unique')
    op.alter_column('compte', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_ledger_entry_reference'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_table('refund')
    op.drop_table('admin_action')
    op.drop_table('admin_user')
    op.drop_index(op.f('ix_risk_event_reference'), table_name='risk_event')
    op.drop_table('risk_event')
    op.drop_index(op.f('ix_payment_event_transaction_reference'), table_name='payment_event')
    op.drop_index(op.f('ix_payment_event_nonce'), table_name='payment_event')
    op.drop_table('payment_event')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
